---
- include: lamp-php56.yml
  when: php_version == 56

- include: lamp-php70.yml
  when: php_version == 70

- include: composer.yml
- include: npm.yml
- include: nginx.yml
- include: sendmail.yml

- include: root-config.yml

- name: Install all updates
  yum: name=* state=latest

- include: php56-memcached.yml
  when:
    - php_version == 56
    - install_php_memcached == true

- include: php70-memcached.yml
  when:
    - php_version == 70
    - install_php_memcached == true